// Copyright 2025 Maksim Shchavelev <maksimshchavelev@gmail.com>

#pragma once

#include <QVector>       // for QVector
#include <functional>    // for std::function
#include <typeindex>     // for std::type_index
#include <unordered_map> // for std:;unordered_map

namespace core {

/**
 * @brief Base class providing a lightweight signal-slot mechanism without QObject.
 *
 * @details
 * `Notifiable` implements a minimal, type-safe **signal dispatching system**
 * inspired by Qt signals and slots, but designed to work in **pure C++**
 * without `QObject`, `Q_OBJECT`, or the Meta-Object Compiler (MOC).
 *
 * The key idea is:
 * - **A signal is represented by a C++ type**
 * - Subscribers connect callbacks to a specific signal type
 * - Signals are dispatched synchronously to all connected slots
 *
 * This class is intended for use in **core / engine / domain layers**
 * where dependency on Qt object model is undesirable, but decoupled
 * notification is still required.
 *
 * ---
 *
 * ## Core concepts
 *
 * ### Signal
 *
 * A **signal** is a user-defined struct type describing a notification.
 * It may be empty (no payload) or contain arbitrary data fields.
 *
 * Example:
 * @code{.cpp}
 * struct Updated {};
 *
 * struct ValueUpdated {
 *     int value;
 * };
 * @endcode
 *
 * The signal type itself serves as a **compile-time identifier**.
 *
 * ---
 *
 * ### Slot
 *
 * A **slot** is a callable with the following signature:
 *
 * @code{.cpp}
 * void(const Signal&)
 * @endcode
 *
 * Slots are registered using `connect<Signal>(...)`.
 *
 * ---
 *
 * ### Dispatching
 *
 * Dispatching a signal notifies all slots connected to the corresponding
 * signal type. Dispatch is **synchronous** and occurs in the calling thread.
 *
 * ---
 *
 * ## Why this class exists
 *
 * Compared to Qt signals and slots, `Notifiable`:
 *
 * - Does not require QObject inheritance
 * - Does not require MOC or meta-object data
 * - Is fully type-safe at compile time
 * - Has zero string-based or runtime reflection
 * - Is trivial to unit-test
 *
 * This makes it suitable for clean, layered architectures where:
 * - Core logic must remain framework-agnostic
 * - UI layers may adapt signals to Qt if needed
 *
 * ---
 *
 * ## Internal design (brief)
 *
 * Internally, slots of different signal types are stored together using
 * **type erasure**:
 *
 * - Externally, slots are strongly typed (`Slot<Signal>`)
 * - Internally, all slots are stored as `std::function<void(const void*)>`
 * - The signal type is restored at dispatch time via `static_cast`
 *
 * This is safe by construction:
 * - Slots are grouped by `typeid(Signal)`
 * - Dispatch always provides the matching signal type
 *
 * ---
 *
 * ## Example 1: Signal without payload
 *
 * @code{.cpp}
 * class Counter final : public core::Notifiable {
 * public:
 *     SIGNAL(updated)
 *
 *     void increment() {
 *         ++m_value;
 *         dispatch(updated{});
 *     }
 *
 * private:
 *     int m_value{0};
 * };
 *
 * Counter c;
 * bool called = false;
 *
 * c.connect<Counter::updated>([&](const Counter::updated&) {
 *     called = true;
 * });
 *
 * c.increment();
 * // called == true
 * @endcode
 *
 * ---
 *
 * ## Example 2: Signal with payload
 *
 * @code{.cpp}
 * class Sensor final : public core::Notifiable {
 * public:
 *     SIGNAL(temperatureChanged, double value)
 *
 *     void set(double t) {
 *         dispatch(temperatureChanged{t});
 *     }
 * };
 *
 * Sensor s;
 *
 * s.connect<Sensor::temperatureChanged>(
 *     [](const Sensor::temperatureChanged& sig) {
 *         qDebug() << "Temperature:" << sig.value;
 *     }
 * );
 *
 * s.set(36.6);
 * @endcode
 *
 * ---
 *
 * ## Threading model
 *
 * - `Notifiable` itself is **not thread-safe**
 * - Signals are dispatched synchronously
 * - If used across threads, external synchronization is required
 *
 * ---
 *
 * ## Relation to Qt
 *
 * `Notifiable` is not a replacement for Qt signals and slots.
 *
 * A common pattern is:
 * - Core / engine layer uses `Notifiable`
 * - UI adapters subscribe to core signals
 * - UI adapters re-emit them as Qt signals (`QObject`)
 *
 * ---
 *
 * @note
 * This class intentionally does not provide:
 * - queued or asynchronous dispatch
 * - automatic disconnection on object destruction
 * - thread affinity handling
 *
 * These features can be built on top if required.
 */
class Notifiable {
  public:
    template <typename Signal> using Slot = std::function<void(const Signal&)>;

    /**
     * @brief Connect a slot to a signal
     *
     * @tparam Signal Signal type (use the struct generated by SIGNAL macro)
     * @param slot Callable taking `const Signal&`
     */
    template <typename Signal> void connect(Slot<Signal> slot) {
        auto& vec = m_slots[typeid(Signal)];
        vec.push_back([slot = std::move(slot)](const void* signal) { slot(*static_cast<const Signal*>(signal)); });
    }

  protected:
    /**
     * @brief Dispatch a signal to all connected slots
     *
     * @tparam Signal Signal type
     * @param signal The signal instance to dispatch
     */
    template <typename Signal> void dispatch(Signal&& signal) {
        for (const auto& slot : m_slots[typeid(Signal)]) {
            slot(&signal);
        }
    }

  private:
    /// Type-erased stored slot
    using ErasedSlot = std::function<void(const void*)>;

    /// Map of signal types to connected slots
    std::unordered_map<std::type_index /* signal name */, QVector<ErasedSlot> /* slots */> m_slots;
};

} // namespace core


/**
 * @brief Macro to declare a signal inside a Notifiable class
 * @param name Signal name
 * @param ... optional fields (types + names) for the signal
 */
#define SIGNAL(name, ...)                                                                                              \
  public:                                                                                                              \
    struct name {                                                                                                      \
        __VA_ARGS__;                                                                                                   \
    };\
