// Copyright 2025 Maksim Shchavelev <maksimshchavelev@gmail.com>

#pragma once

#include <QVector>       // for QVector
#include <functional>    // for std::function
#include <typeindex>     // for std::type_index
#include <unordered_map> // for std:;unordered_map

namespace core {

/**
 * @brief Base class providing a lightweight signal-slot mechanism without QObject.
 *
 * @details
 * `Notifiable` implements a minimal, type-safe **event dispatching system**
 * inspired by Qt signals and slots, but designed to work in **pure C++**
 * without `QObject`, `Q_OBJECT`, or the Meta-Object Compiler (MOC).
 *
 * The key idea is:
 * - **An event is represented by a C++ type**
 * - Subscribers connect callbacks to a specific event type
 * - Events are dispatched synchronously to all connected slots
 *
 * This class is intended for use in **core / engine / domain layers**
 * where dependency on Qt object model is undesirable, but decoupled
 * notification is still required.
 *
 * ---
 *
 * ## Core concepts
 *
 * ### Event
 *
 * An **event** is a user-defined struct type describing a notification.
 * It may be empty (no payload) or contain arbitrary data fields.
 *
 * Example:
 * @code{.cpp}
 * struct Updated {};
 *
 * struct ValueUpdated {
 *     int value;
 * };
 * @endcode
 *
 * The event type itself serves as a **compile-time identifier**.
 *
 * ---
 *
 * ### Slot
 *
 * A **slot** is a callable with the following signature:
 *
 * @code{.cpp}
 * void(const Event&)
 * @endcode
 *
 * Slots are registered using `connect<Event>(...)`.
 *
 * ---
 *
 * ### Dispatching
 *
 * Dispatching an event notifies all slots connected to the corresponding
 * Event type. Dispatch is **synchronous** and occurs in the calling thread.
 *
 * ---
 *
 * ## Why this class exists
 *
 * Compared to Qt signals and slots, `Notifiable`:
 *
 * - Does not require QObject inheritance
 * - Does not require MOC or meta-object data
 * - Is fully type-safe at compile time
 * - Has zero string-based or runtime reflection
 * - Is trivial to unit-test
 *
 * This makes it suitable for clean, layered architectures where:
 * - Core logic must remain framework-agnostic
 * - UI layers may adapt signals to Qt if needed
 *
 * ---
 *
 * ## Internal design (brief)
 *
 * Internally, slots of different event types are stored together using
 * **type erasure**:
 *
 * - Externally, slots are strongly typed (`Slot<Event>`)
 * - Internally, all slots are stored as `std::function<void(const void*)>`
 * - The event type is restored at dispatch time via `static_cast`
 *
 * This is safe by construction:
 * - Slots are grouped by `typeid(Event)`
 * - Dispatch always provides the matching event type
 *
 * ---
 *
 * ## Example 1: Event without payload
 *
 * @code{.cpp}
 * class Counter final : public core::Notifiable {
 * public:
 *     EVENT(updated)
 *
 *     void increment() {
 *         ++m_value;
 *         dispatch(updated{});
 *     }
 *
 * private:
 *     int m_value{0};
 * };
 *
 * Counter c;
 * bool called = false;
 *
 * c.connect<Counter::updated>([&](const Counter::updated&) {
 *     called = true;
 * });
 *
 * c.increment();
 * // called == true
 * @endcode
 *
 * ---
 *
 * ## Example 2: Event with payload
 *
 * @code{.cpp}
 * class Sensor final : public core::Notifiable {
 * public:
 *     EVENT(temperatureChanged, double value)
 *
 *     void set(double t) {
 *         dispatch(temperatureChanged{t});
 *     }
 * };
 *
 * Sensor s;
 *
 * s.connect<Sensor::temperatureChanged>(
 *     [](const Sensor::temperatureChanged& sig) {
 *         qDebug() << "Temperature:" << sig.value;
 *     }
 * );
 *
 * s.set(36.6);
 * @endcode
 *
 * ---
 *
 * ## Threading model
 *
 * - `Notifiable` itself is **not thread-safe**
 * - Events are dispatched synchronously
 * - If used across threads, external synchronization is required
 *
 * ---
 *
 * ## Relation to Qt
 *
 * `Notifiable` is not a replacement for Qt signals and slots.
 *
 * A common pattern is:
 * - Core / engine layer uses `Notifiable`
 * - UI adapters subscribe to core events
 * - UI adapters re-emit them as Qt signals (`QObject`)
 *
 * ---
 *
 * @note
 * This class intentionally does not provide:
 * - queued or asynchronous dispatch
 * - automatic disconnection on object destruction
 * - thread affinity handling
 *
 * These features can be built on top if required.
 */
class Notifiable {
  public:
    template <typename Event> using Slot = std::function<void(const Event&)>;

    /**
     * @brief Connect a slot to a event
     *
     * @tparam Event Event type (use the struct generated by EVENT macro)
     * @param slot Callable taking `const Event&`
     */
    template <typename Event> void connect(Slot<Event> slot) {
        using CleanEvent = std::remove_cvref_t<Event>;
        auto& vec = m_slots[key<CleanEvent>()];
        vec.push_back([slot = std::move(slot)](const void* event) { slot(*static_cast<const CleanEvent*>(event)); });
    }

  protected:
    /**
     * @brief Dispatch a event to all connected slots
     *
     * @tparam Event Event type
     * @param event The event instance to dispatch
     */
    template <typename Event> void dispatch(Event&& event) const {
        using CleanEvent = std::remove_cvref_t<Event>;
        for (const auto& slot : m_slots[key<CleanEvent>()]) {
            slot(&event);
        }
    }

  private:
    /// Type-erased stored slot
    using ErasedSlot = std::function<void(const void*)>;

    /// Map of signal types to connected slots
    std::unordered_map<QString /* event name */, QVector<ErasedSlot> /* slots */> m_slots;

    template <typename T>
    static QString key() {
        return typeid(T).name();
    }
};

} // namespace core


/**
 * @brief Macro to declare an event inside a Notifiable class
 * @param name Event name
 * @param ... optional fields (types + names) for the signal
 */
#define EVENT(name, ...)                                                                                               \
  public:                                                                                                              \
    struct name {                                                                                                      \
        __VA_ARGS__;                                                                                                   \
    };\
